services:
  tracker:
    build: 
      context: .
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy
      migrate: 
        condition: service_completed_successfully
  migrate:
    build: 
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tracker
      TZ: "Europe/Moscow"
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 1s
      timeout: 2s
      start_period: 1s
      start_interval: 1s
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
